Check for NO linters errors
eri8-9/Review-One-Of-My-Last-Projects pull request #1
Opened 2021-06-02 16:05 UTC by eri8-9

Add index.html

Add style.css

Add .github/

2021-06-02 17:58 UTC, eri8-9 commented on index.html
> +    <nav id="navbar" >
Try to not leave space before the arrow.

2021-06-02 17:58 UTC, eri8-9 commented on index.html
> +
Try to not leave space between the lines.

2021-06-02 17:58 UTC, eri8-9 commented on index.html
> +        <code></code>
If you are not using these tags it is better if you removed them from the code to have a clean code.

2021-06-03 00:15 UTC, SpaYco requested changes
Hi @eri8-9, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [x] Add a summary for your review (you can use this as a template)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 00:15 UTC, Spayco commented on index.html
> +    <nav id="navbar" >
- kindly phrase the comments politely, as suggestions instead of orders. For example:
  * This is a polite suggestion: *"I think it would be better to use semantic tags"*
  * This reads as an order: *"Use semantic tags"*
- please include an explanation, a "why", for each requested change. For example:
  * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
  * This request lacks a "why": *Why don't you use an article tag here instead of a div?*

2021-06-03 00:15 UTC, Spayco commented on index.html
> +        <code></code>
everything looks good here 💯

2021-06-03 00:15 UTC, Spayco commented on index.html
> +
- kindly phrase the comments politely, as suggestions instead of orders. For example:
  * This is a polite suggestion: *"I think it would be better to use semantic tags"*
  * This reads as an order: *"Use semantic tags"*
- please include an explanation, a "why", for each requested change. For example:
  * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
  * This request lacks a "why": *Why don't you use an article tag here instead of a div?*

2021-06-03 15:44 UTC, christianotieno requested changes
Hi @eri8-9, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- I think this and the first review are good examples of summary reviews that should be accompanying your review. I would welcome you to use them as a  good reference point. Kindly find a detailed explanation of this in the inline comment below. Thank you!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 15:44 UTC, christianotieno commented on style.css
> +}
Required change: 

- [ ] For all of our code reviews, we are required to always accompany our reviews with a special summary that would act as a gateway and highlight the reviews themselves. It is great that you have mastered the lessons on how to conduct reviews using the inline comments and the review features. What is currently missing is the `summary review`. I think it would e great if you added it to this project before we can consider this as complete don't you think? :smile:

2021-06-03 15:54 UTC, eri8-9 commented on style.css
> +}
Hello thanks for advising me, would you show me where I can do my summary? I'm lost.

2021-06-03 16:18 UTC, christianotieno commented on style.css
> +}
We have a lesson on how to add our summary. Take note of the first instructions where you will need to click on the `File Changes` button on this pull request to do so. :octocat: 


- Here is a link to t[he part of the lesson about communication](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate) that you can use.

Please don't hesitate to comment on this pull request if you still feel stuck. The resources shared above would be enough to get you over the line though 😄

2021-06-03 16:18 UTC, eri8-9 commented on index.html
> +
- [ ] Hello!

2021-06-03 16:37 UTC, eri8-9 reviewed
Hi @eri8-9, 

Good job so far!

## Learning objectives

- Apply best practices in HTML code.
- Use semantic HTML tags.
- Use CSS selectors correctly.
- Use CSS box model.
- Perform a code review for yourself on a past project.

## Project requirements

- Create a new empty repo.
- Copy your code from the project that you completed during the Admissions Trial: - If you do not have the code from the Admissions Trial ask someone from your Standup Team to share their code with you. In that case, remember to add an attribution note and acknowledgment in your README file.
- Create a new branch for your copied code.
- Open a pull request.
- Play the role of the Code Reviewer:
- Follow the list from the article "How to give a code review?".
- Check if you have used semantic HTML tags.
- Check if you applied HTML & CSS best practices.
- Add as many comments as possible in the given time and finish your review. Remember to add a minimum of 2 comments - you will definitely find something that could have been done better!
- Copy a link to the pull request and ask for a code review in your Student Dashboard as usual. (The only difference will be that the Code Reviewer won't check your code but the review you performed - isn't it a code review inception? ;))


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 16:41 UTC, eri8-9 commented on style.css
> +}
I did my summary. is it right like that?

2021-06-03 17:20 UTC, descholar-ceo requested changes
Hi @eri8-9 :handshake: :handshake: :handshake:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [x] You have a very good progress so far, the review summary is present now, but it still needs some adjustments, see that you have already given suggestions within your inline comments, now this review summary is just like giving a short overview of the whole review process, just as explained by @christianotieno [here](https://github.com/eri8-9/Review-One-Of-My-Last-Projects/pull/1#discussion_r644908764). Now what you are required to do, try to rephrase your summary making sure that it is a summary which is highlighting the overview of the whole review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 20:39 UTC, Spayco approved these changes
Hi @eri8-9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 20:50 UTC, merged